Still debugging GH action agenda fails
lib test works, so drop from Travis

diff --git a/.github/workflows/unittestagenda.yml b/.github/workflows/unittestagenda.yml
--- a/.github/workflows/unittestagenda.yml
+++ b/.github/workflows/unittestagenda.yml
@@ -47,5 +47,7 @@ jobs:
     - name: test agenda code
       run: |
         cd www/board/agenda
-        npm install # fails under rake
+        which -a npm || true
+        echo $PATH
+        # npm install # fails under rake
         bundle exec rake
